module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Families',
    'Kid',
    'Magic',
    'Magic Bridge',
    'Water'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Playground',
    'Playgrounds',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Cliffs',
    'Hollow'
]